version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_USER=user
      - MARIADB_PASSWORD=qwerty
      - MARIADB_DATABASE=db_learn
    ports:
      - '3306:3306'
    volumes:
      - db_learn:/var/lib/mysql
  
volumes:
  db_learn: